### ISSUE TITLE
[BUG] *tamyyyy#6177* - *Comando de Work*

### ISSUE THREAD

**Issue by tamyyyyyyyyyy** [jurgenjacobsen/nico#5]
**Descreva o bug**
O comando de work não funcionou

**Reproduzir**
/work > clicar no comando sugerido

**Comportamento esperado**
depositar alguma quantia na minha carteira

**Capturas de tela** *(Opicional)*
![image](https://user-images.githubusercontent.com/89816015/132996596-d7b301bd-6b36-4d02-b012-848ac79634a3.png)
**Contexto adicional** *(Opicional)*
bug ocorreu pelo celular.

**Comment by jurgenjacobsen** [comment]
Sabe me dizer se o bot tava online na hora do bug?

**Comment by tamyyyyyyyyyy** [comment]
> Sabe me dizer se o bot tava online na hora do bug?

acho que sim, pois ele estava aparente na lista de membros na hora

**Comment by jurgenjacobsen** [comment]
Ok, a princípio depois dos testes que eu fiz possa ter sido um pequeno probleminha no lado do Discord, obg tamy <3
