### ISSUE TITLE
[SUG] *!ka1qux#5048* - *adicionar  uma informação do valor de quanto será as contas no /fabric*

### ISSUE THREAD

**Issue by ka1qux** [jurgenjacobsen/nico#6]
**Sua sugestão está relacionada a um problema? Por favor descreva.**
Não.

**Descreva a solução que você gostaria**
Quando digitar o comando /fabric e estiver no dia de pagar as contas, aparecer uma informação do valor das contas dentro do comando.

**Contexto adicional**
![Capturar](https://user-images.githubusercontent.com/80919110/132999555-8707ca61-c538-4ed4-95a4-0637664f7367.PNG)

**Comment by jurgenjacobsen** [comment]
Função já existe, o valor a se pagar pelas contas aparecerá no risco vermelho da print abaixo.

![image](https://user-images.githubusercontent.com/30883538/132999757-cbf821e8-fb56-479a-8543-b988808be823.png)
